// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgtuluqtmclnocykyeih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNndHVsdXF0bWNsbm9jeWt5ZWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzgwOTIsImV4cCI6MjA3NDQ1NDA5Mn0.JissZFTAM5zGB0fmcP1Xv-WGNxb2TohEY7vJ7BTGIWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});